/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.Project;
import Entity.WorkOn;
import Entity.phones;
import companytest.Tools;

/**
 *
 * @author 911
 */
public class frmTest extends javax.swing.JFrame {

    /**
     * Creates new form frmTest
     */
    public frmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntestDept = new Controls.JBotton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltest1 = new javax.swing.JTable();
        btnnn = new Controls.JBotton();
        BtnTestEmp = new Controls.JBotton();
        PHtest = new Controls.JBotton();
        prTest = new Controls.JBotton();
        BTNTESTWORK = new Controls.JBotton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btntestDept.setText("Test Department");
        btntestDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestDeptActionPerformed(evt);
            }
        });

        tbltest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tbltest);

        tbltest1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbltest1);

        btnnn.setText("jBotton1");
        btnnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnnActionPerformed(evt);
            }
        });

        BtnTestEmp.setText("TesTEmpLoYee :D");
        BtnTestEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTestEmpActionPerformed(evt);
            }
        });

        PHtest.setText("Phones Tes");
        PHtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHtestActionPerformed(evt);
            }
        });

        prTest.setText("Prtest");
        prTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prTestActionPerformed(evt);
            }
        });

        BTNTESTWORK.setText("TEST WORKON");
        BTNTESTWORK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTESTWORKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnTestEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(btntestDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PHtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNTESTWORK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btntestDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(PHtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnTestEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(prTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(BTNTESTWORK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntestDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestDeptActionPerformed
         Department dept = new Department();
         //dept.setDEPTNO(1);
         //dept.setDEPTNAME(" bi");
         //dept.setLocation("Masor");
         //dept.add();
         //dept.update();
         //dept.delete();
         //dept.getAllRows(tbltest);
         // Tools.msgBox(dept.getAutoNumber());
         //dept.getCustomRows("Select * from department", tbltest);
         //dept.getOneRow(tbltest);
         //Tools.msgBox(dept.getValueByName(" bi"));
         //Tools.msgBox(dept.getNameByValue("3"));
         
        
    }//GEN-LAST:event_btntestDeptActionPerformed

    private void btnnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnnActionPerformed
         boolean confirm = Tools.confirmMsg("Hello!?");
         if (confirm) Tools.msgBox("Yes");
         else Tools.msgBox("Other");
    }//GEN-LAST:event_btnnnActionPerformed

    private void BtnTestEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTestEmpActionPerformed
         Employee emp = new Employee();
       emp.setEMPNO(1);
      //  emp.setEMPNAME("bssakb");
      //  emp.setBIRTHDATE("2322-8-9");
      //  emp.setEMPSALARY(774000);
      //  emp.setEMPHIRDATE("2022-3-16");
      //  emp.setEMPADD("hha");
      //  emp.setDEPTNO(2);
      //  emp.add();
      //  emp.delete();
      //  emp.update();
      //  emp.getAllRows(tbltest);
      // Tools.msgBox(emp.getAutoNumber());
      // emp.getCustomRows("select * from employee", tbltest);
      // Tools.msgBox(emp.getNameByValue("1"));
      //Tools.msgBox(emp.getValueByName("Yusuf"));
      // emp.getOneRow(tbltest);
   
      
    }//GEN-LAST:event_BtnTestEmpActionPerformed

   
    private void PHtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHtestActionPerformed

         phones P = new phones();
        P.setEMPNO(1);

        P.setPhone("011");
        P.add();
    }//GEN-LAST:event_PHtestActionPerformed

    private void prTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prTestActionPerformed
       Project p = new Project();
     // p.setLocation("Bani Suef");
    //  p.setProjectName("SalaahSalem");
     // p.setProjectNO(2);
   //   p.setDEPTNO(1);
   //  p.add();
     // p.update();
    // p.delete();
   // Tools.msgBox(p.);
  // p.getAllRows(tbltest);
  //p.getOneRow(tbltest);
 // String StrStatment="Select * from project";
 // p.getCustomRows(StrStatment, tbltest);
 //p.getValueByName("SalaahSalem");
 //Tools.msgBox(p.getValueByName("Salaah_Salem"));
 Tools.msgBox(p.getNameByValue("1"));
    }//GEN-LAST:event_prTestActionPerformed
WorkOn w = new WorkOn();
    private void BTNTESTWORKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTESTWORKActionPerformed

     // w.setEMPNO(6);
     // w.setPROJECTNO(4);
       // w.add();
       // w.delete();
      w.getAllRows(tbltest);
      // w.getOneRow(tbltest);
      //w.getCustomRows("SELECT * from workon", tbltest);
    }//GEN-LAST:event_BTNTESTWORKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         w.getAllRows(tbltest);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.JBotton BTNTESTWORK;
    private Controls.JBotton BtnTestEmp;
    private Controls.JBotton PHtest;
    private Controls.JBotton btnnn;
    private Controls.JBotton btntestDept;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Controls.JBotton prTest;
    private javax.swing.JTable tbltest;
    private javax.swing.JTable tbltest1;
    // End of variables declaration//GEN-END:variables
}
